//MIDDLEWARE
export const MIDDLEWARE_TOGGLE = "MIDDLEWARE_TOGGLE";
export const MIDDLEWARE = "MIDDLEWARE";
export const ERROR_MIDDLEWARE = "ERROR_MIDDLEWARE";

//login e inicio de sesion
export const types = {
  MOSTRAR_ALERTA: "[AUTH] mostrar alerta",
  OCULTAR_ALERTA: "[AUTH] ocultar alerta",
  LOGIN_ERROR: "[AUTH] login error",
  LOGIN_EXITOSO: "[AUTH] login existoso",
  OBTENER_USUARIO: "[AUTH] obtener usuario",
  CERRAR_SESION: "[AUTH] cerrar sesion",
  INICIAR_SESION: "[AUTH] inicia sesion",
};

//Forgot Password
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

//Errors API
export const SHOW_ERRORS_API = "SHOW_ERRORS_API";

// ========================
// Systems
// ========================
export const GET_SYSTEMS = "GET_SYSTEMS";
export const ADD_SYSTEM = "ADD_SYSTEM";
export const UPDATE_SYSTEM = "UPDATE_SYSTEM";
export const DELETE_SYSTEM = "DELETE_SYSTEM";
export const SYSTEM_ERROR = "SYSTEM_ERROR";

// COURSES
// ====================
export const OBTENER_COURSES = "OBTENER_COURSES";
export const OBTENER_COURSE = "OBTENER_COURSE";
export const AGREGAR_COURSE = "AGREGAR_COURSE";
export const ACTUALIZAR_COURSE = "ACTUALIZAR_COURSE";
export const ELIMINAR_COURSE = "ELIMINAR_COURSE";

// USER TYPES
export const GET_USERS = "GET_USERS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_ERROR = "USER_ERROR";

// Eventos
export const EVENTOS_CARGANDO = "EVENTOS_CARGANDO";
export const EVENTOS_NO_CARGANDO = "EVENTOS_NO_CARGANDO";
export const OBTENER_EVENTOS = "OBTENER_EVENTOS";
export const CREAR_EVENTO = "CREAR_EVENTO";
export const ACTUALIZAR_EVENTO = "ACTUALIZAR_EVENTO";
export const ELIMINAR_EVENTO = "ELIMINAR_EVENTO";
export const OBTENER_EVENTO = "OBTENER_EVENTO";
export const LIMPIAR_EVENTO_ACTUAL = "LIMPIAR_EVENTO_ACTUAL";
export const EVENTO_ERROR = "EVENTO_ERROR";
export const OBTENER_TOPSALES = "OBTENER_TOPSALES";
export const LIMPIAR_ERROR_EVENTO = "LIMPIAR_ERROR_EVENTO";
export const RESET_SUCCESS_EVENTO = "RESET_SUCCESS_EVENTO";

// Productos
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

// Ordenes
export const ORDERS_CARGANDO = 'ORDERS_CARGANDO';
export const ORDERS_NO_CARGANDO = 'ORDERS_NO_CARGANDO';
export const OBTENER_ORDERS = 'OBTENER_ORDERS';
export const ACTUALIZAR_ORDER = 'ACTUALIZAR_ORDER';
export const OBTENER_ORDER = 'OBTENER_ORDER';
export const ORDER_ERROR = 'ORDER_ERROR';
export const LIMPIAR_ORDER_ACTUAL = 'LIMPIAR_ORDER_ACTUAL';
export const LIMPIAR_ERROR_ORDER = 'LIMPIAR_ERROR_ORDER';
export const RESET_SUCCESS_ORDER = 'RESET_SUCCESS_ORDER';
export const OBTENER_ORDENES_ACTIVAS = 'OBTENER_ORDENES_ACTIVAS';
export const OBTENER_ORDENES_LIQUIDADAS = 'OBTENER_ORDENES_LIQUIDADAS';
export const OBTENER_ORDENES_ENVIO_PAGADO = 'OBTENER_ORDENES_ENVIO_PAGADO';
export const OBTENER_ORDENES_ENVIADAS = 'OBTENER_ORDENES_ENVIADAS';
